In [11]:
import numpy as np


In [12]:
a = np.arange(5)
b = a
b[2] = 99
print(a)

[ 0  1 99  3  4]


In [13]:
np.array([1,2,3]) is np.array([1,2,3])

False

In [14]:
arr = np.arange(8).reshape(2,2,2)
print(arr.shape)

(2, 2, 2)


In [15]:
# a = np.array([1,2,3])
# print(a+a[:,None]).shape

In [16]:
arr = np.array([1 , 2.0 , True])
print(arr)

[1. 2. 1.]


In [17]:
a = np.array([np.nan , 1, 2])
print(a)
print(np.sum(a))

[nan  1.  2.]
nan


In [18]:
a = np.arange(4)
print(a[::-1])

[3 2 1 0]


In [19]:
a = np.arange(6)
mask = a%2 == 0
print(a)
print(mask)
print(a[mask][1])

[0 1 2 3 4 5]
[ True False  True False  True False]
2


In [20]:
a = np.arange(10)
print(a)
print(a[::2])
print(a[::-1])
print(a[::2][::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[8 6 4 2 0]


In [21]:
a = np.array([1,2,3])
b = np.array([2])
print(a*b)

[2 4 6]


In [22]:
a = np.ones((2,3))
b = np.ones((3,1))

print(a)
print(b)
print((a@b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1.]
 [1.]
 [1.]]
[[3.]
 [3.]]


In [23]:
a = np.arange(9).reshape(3,3)
print(a.T.flatten())

[0 3 6 1 4 7 2 5 8]


In [24]:
a = np.array([1,2,3])
b = a.view()
b[0] = 100
print(a)

[100   2   3]


In [25]:
a = np.zeros((2,1))
b = np.zeros((1,3))

print(a)
print(b)
print((a+b))

[[0.]
 [0.]]
[[0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
a = np.array([1.7 , 2.9 , -1.1],dtype=int)
print(a)

[ 1  2 -1]
